server:
  port: 8080
spring:
  application:
    name: Gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
#     gateway:
#       routes:
#         - id: r1
#            uri: lb://student-service
#            predicates:
#             - Path= /Students/**
#             - Path= /Classroom/
#         - id: r2
#            uri: lb://course-service
#            predicates:
#             - Path= /Courses/
#         - id: r3
#            uri: lb://professors-service
#            predicates:
#             - Path= /Professors/
#         - id: r4
#            uri: lb://absence-service
#            predicates:
#              - Path= /Absences/